version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./backend/Docker/app/Dockerfile
    volumes:
      - ./backend/src:/app
  web:
    build:
      context: .
      dockerfile: ./backend/Docker/web/Dockerfile
    ports:
      - 8081:80
    depends_on:
      - app
    volumes:
      - ./backend/src:/app
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Docker/app/Dockerfile
    volumes:
      - ./frontend/src:/app
    command: 'yarn dev'
    ports:
      - 3000:3000
  db:
    build:
      context: .
      dockerfile: ./backend/docker/db/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: daiji_kato
      MYSQL_PASSWORD: 5w1h3581
      MYSQL_ROOT_PASSWORD: 005w1H3581
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume: